### ISSUE TITLE
Please provide an AppImage for download on GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [Sn8z/Poddr#1]
Please provide an AppImage for download on GitHub Releases. The project is already configured for it:

https://github.com/Sn8z/Poddr/blob/e542f7503fdd3a5f45a8e12c0d86798e9a966988/package.json#L30

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by Sn8z** [comment]
Thanks for the great feedback and tips!
I've been slacking when it comes to maintaining the GitHub Releases but I will make sure to post an updated AppImage together with an updated .exe aswell in the coming days! 💃

**Comment by Sn8z** [comment]
[v1.0.5 is now available](https://github.com/Sn8z/Poddr/releases/tag/1.0.5) and I'm therefore closing this issue. :smiley:

**Comment by probonopd** [comment]
Thanks. Added to https://appimage.github.io/Poddr/
