### ISSUE TITLE
Apple API returns 401

### ISSUE THREAD

**Issue by Sn8z** [Sn8z/Poddr#2]
Currently the storefronts endpoint(https://api.music.apple.com/v1/storefronts) returns a 401 Unauthorized error, not sure why as it shouldn't require any special kind of key etc. [Get all storefronts](https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/AppleMusicWebServicesReference/Getallstorefronts.html#//apple_ref/doc/uid/TP40017625-CH132-SW1)
Not the biggest issue since we can still search and use Poddr, the only issue is that we can't change the default region to use. There's a built in fallback list of regions that is kicking in atm but this should be solved.

**Comment by Sn8z** [comment]
The API endpoint is now working properly again so the issue will be closed, but there's a new improved fallback in the works that should help with this kind of issue in the future.

**Comment by Sn8z** [comment]
Error seems to come and go so I will reopen the issue... But I managed to get a up to date JSON during the short time it did work so I should be able to make a great fallback function. If the API keeps on behaving like this I just might decide to only rely on a local JSON with info for the storefronts.

**Comment by shkar62** [comment]
I am getting 401 unauthorised every time, I hit the API. The same error comes while I do the store front lookup too. Can somebody assist?

**Comment by Sn8z** [comment]
@shkar62 I managed to save a JSON response of the endpoint for all storefronts which you could copy and use while Apple is sorting out their issues...
[Get all storefronts](https://github.com/Sn8z/Poddr/blob/master/app/scripts/storefronts.json)

When it comes to the lookup for separate storefronts I'm afraid I can't help you :(

**Comment by Sn8z** [comment]
This issue will now be closed since Poddr is now using a local copy of the API response. The API seems to be more reliable and I might consider switching back to it in the future.
