### ISSUE TITLE
Bug: Current play time is lost on restart

### ISSUE THREAD

**Issue by yougotwill** [Sn8z/Poddr#347]
**Describe the bug**
If you close and reopen Poddr it remembers the podcast episode you were listening to but not the play time when you closed it. Basically you have to remember where you were in the podcast.

**To Reproduce**
1. Play any podcast episode
2. Pause at any time.
3. Close and reopen Poddr
4. See play time resets to 00:00:00

**Expected behavior**
When you close and reopen Poddr it should remember how far you were in a podcast episode so that you can continue listening from where you left off.

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - Version [e.g. 10.14.2]

Other than that I'm looking forward to the Angular upgrade and the offline playback ;) Keep up the good work @Sn8z !

**Comment by Sn8z** [comment]
Hey @yougotwill! :)
You are right, this should be added aswell :dancer:

**Comment by Sn8z** [comment]
This is fixed in Poddr 2.0.0 which just got released :smiley: Feel free to reopen this issue if things aren't working as expected :dancer:
