### ISSUE TITLE
Bug: Cannot Get Podcast RSS Feed

### ISSUE THREAD

**Issue by UsefulParamedic** [Sn8z/Poddr#378]
Searching for pods are possible, but when it is time to open a podcast list and play, it never loads any, and reports "Cannot Get Podcast RSS Feed". It is not my internet connection.

**Comment by Sn8z** [comment]
Hey there @UsefulParamedic , sorry for responding slowly. 

I do need some more information to help you, in the future it's good practice to use the template when creating new issues, it makes everything smoother :smiley: 

So what version of Poddr are you using?
What's your operating system and if it's a linux distro what desktop environment are you using?
Is this your first time using Poddr or have it worked previously for you?

There's also a log file you can look at to help find the error when it happens, see [here](https://github.com/Sn8z/Poddr/wiki/Error-Logs).

**Comment by Sn8z** [comment]
@UsefulParamedic Any news on this issue?

**Comment by Sn8z** [comment]
I'm closing this issue for now due to lack of response and information.
If anyone comes across this in the future feel free to comment here so we can reopen if needed :man_dancing:
