### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by JackNavarra** [Sn8z/Poddr#52]
I'm not sure if this is the right place to report this, my apologies if it is not.  

The program (or app) stopped working properly after using it for couple of days. I'm now experiencing a strange behaviour, when I start it, the  window appears with its dark grey background but with nothing on it. Please see the attachment. 

I'm using Ubuntu 18.04 recently updated. I tried an uninstall/install cycle but it didn't work. 

I would be glad if I could use this program again. It just worked fine and was simple. 

![screenshot from 2018-11-13 12-12-41](https://user-images.githubusercontent.com/45001148/48409919-7498ea80-e73d-11e8-96e1-c7900b04ac2a.png)

**Comment by Sn8z** [comment]
Hi @JackNavarra! Are you perhaps using the snap version of Poddr? If so I guess there are some issues with the 1.0.9 update released last week. If you could launch the program from a terminal and return the output here it would be great 💃

**Comment by Sn8z** [comment]
This is btw absolutely the right place to post issues! 👍

**Comment by JackNavarra** [comment]
Hi Marcus! Thank you for your response.

Yes, I am using the snap version and it is 1.0.9.

Here is the screen output when I launch the program in a terminal:


```
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
[15:13:32.339] [info] gnome
[15:13:32.342] [info] Error: No introspectable
    at /snap/poddr/2/resources/app.asar/node_modules/dbus/lib/bus.js:129:15

[15:13:32.343] [info] mate
[15:13:32.343] [info] Error: No introspectable
    at /snap/poddr/2/resources/app.asar/node_modules/dbus/lib/bus.js:129:15

[15:13:32.739] [info] Settings are stored at /home/jackn/snap/poddr/2/.config/poddr/storage
[15:13:32.805] [info] Fetching storefronts...
[15:13:32.823] [info] Done fetching storefronts.
[15:13:32.908] [info] Loaded CSS color variable.
[15:13:32.911] [info] Fetching podcasts...
[15:13:33.287] [info] Found 50 podcasts.

```

**Comment by JackNavarra** [comment]
I'm using Gnome 3.28.2.

I tried reverting the version but didn't work:
`error: cannot revert "poddr": no revision to revert to`

Do you think I should try it manually? i.e. compiling and installing the version 1.0.8 from the source? I guess that is available on github.

**Comment by Sn8z** [comment]
I guess that means you've never had 1.0.8 installed?
`snap list --all` should show if you've had any prevision version installed.
Do you know if 1.0.9 have worked at any point for you?
It could be an issue with the 'state' of the player.
In `/home/jackn/snap/poddr/2/.config/poddr/storage` there should be multiple JSON files, try moving `region.json / volume.json / playerState.json / prevPlayed.json`one by one to another location(if this helps I would love to see the content of the file :dancer: ) and start Poddr inbetween. These files store values between sessions and if they contain something weird it could cause issues.

**Comment by JackNavarra** [comment]
No, I have never had 1.0.8 installed. I just installed it couple of days ago (v1.0.9) and used for a few days with no problem. 

`/home/jackn/snap/poddr/2/.config/poddr/storage` is empty.

**Comment by Sn8z** [comment]
That sounds weird, are you sure that nautilus is showing all files?
Can you confirm that the directory is empty by running 
`ls -la /home/jackn/snap/poddr/2/.config/poddr/storage`
You could also try to download and run the AppImage version of Poddr found under releases and see if that works for you. The snap version and the AppImage version uses different folders for storage so it will behave like a completely new installation of Poddr.

I will install a Ubuntu machine later today and see if I'm able to reproduce the error in some way. I will also improve the logging and publish an updated 1.0.9 version asap.

**Comment by Sn8z** [comment]
@JackNavarra Just got my Ubuntu installation up and running and can confirm that I get the same crash on a fresh install, will look into it and get back to you here :)

**Comment by Sn8z** [comment]
@JackNavarra So I've just uploaded a new revision to snapcraft :dancer: 
`snap refresh poddr`
It would be awesome if you could take a look and see if things work as expected :)
There was an issue with a dependency that for some reason doesn't work well with Ubuntu 18.04 atm. I'm honestly not sure why it only crashes in Ubuntu but I will have to look into that more thoroughly in the coming weeks.

**Comment by JackNavarra** [comment]
Hi @Sn8z 

I'm sorry for the long break. I checked already the folder `ls -la /home/jackn/snap/poddr/2/.config/poddr/storage` and didn't return with the expected content, it is empty.

I also tried `snap refresh poddr` and I got:
`snap "poddr" has no updates available`

It is weird, that I didn't try to launch Poddr before the `refresh` command, but it just worked after `refresh` even though there were no updates. I don't know if this is because you didn't specify a new version number for the modifications you have done but it anyway installed the modified version. I don't know how snap works, to be honest. 

FYI: After successful launch I checked once again if the above mentioned folder has contents and it has not. I did a search on my computer where the files mentioned in this post are:
[https://github.com/Sn8z/Poddr/issues/52#issuecomment-438718480](url) 
and failed to locate them.

Thank you very much for your support. I'm currently enjoying my podcasts via poddr! I hope this time it will not be short-lived.

**Comment by Sn8z** [comment]
No worries :)

Hmm, it's indeed weird that the folder is empty.. Can you save favourites and are volume and last played podcast stored between sessions? The number represents the revision of Poddr so the 2 should now be a 3.

Snaps are auto-updating, the refresh command is just a way to force check for updates so that works as expected ^^ By typing `snap list` you can see both the version and revision of a snap which can be useful sometimes.

I'm glad that it now works again and thanks for making me aware of the issue! If any new problems/bugs arises feel free to create a new issue :dancer:

**Comment by JackNavarra** [comment]
I'm not sure if I understand your request properly:
> Can you save favourites and are volume and last played podcast stored between sessions? 

If you are asking whether I'm able to save favourites, to recover the last episode played and the volume level between sessions (quiting and launching cycles), then the answer is: yes, I am. 

On the other hand, `/home/jackn/snap/poddr/3/.config/poddr/storage/` contains some of the *.json files you mentioned:
`1048450387.json`
`1083150785.json`
`1089143225.json`
`playerState.json`
`prevPlayed.json`
`volume.json`

But, `/home/jackn/snap/poddr/2/.config/poddr/storage/` is still empty (I guess this is the configuration folder for the revision 2)

> The number represents the revision of Poddr so the 2 should now be a 3
Yes, the revision number is now 3.

Thank you, again, for your support.

**Comment by Sn8z** [comment]
Yes, that was what I meant :+1:
Things seems to be working as expected!
I'll probably have to make some kind of FAQ or explanation of the different .json files in the future.

Thanks to you aswell for reporting the issue! I will make a greater effort in the future to make sure it runs well on Ubuntu(18.04) before updating the stable release :dancer:
