### ISSUE TITLE
Show response when clicking the filter icon

### ISSUE THREAD

**Issue by yougotwill** [Sn8z/Poddr#55]
<img width="1440" alt="screen shot 2018-11-25 at 2 51 33 pm" src="https://user-images.githubusercontent.com/14887287/48979323-fd127600-f0c1-11e8-802e-eb329ebf854d.png">

Minor issue but worth pointing out. Showing some sort of response when clicking this would be great. Thank you and keep up the good work :) 

P.S. I know know the episodes change order but still bugs me a little 😂

**Comment by Sn8z** [comment]
This is something I've overlooked :D I will make sure to fix this in 1.1.0!
Great feedback :dancer:

**Comment by Sn8z** [comment]
The episode sidebar is now updated with the 1.1.0 release so I'm closing this issue :+1:
