### ISSUE TITLE
Offline playback

### ISSUE THREAD

**Issue by yougotwill** [Sn8z/Poddr#56]
If you could get Poddr to download and store podcast episodes for offline playback then you will have reached perfection 😄

**Comment by Sn8z** [comment]
I would love to make this feature and include it in Poddr but there's a few things I gotta do before that :)
I will add it to the pipeline of stuff to do ^^

**Comment by mingbrit23** [comment]
Thanks for a great program, but I would definitely like to second the request for download capabilities.

**Comment by rivman** [comment]
That would be such a great feature, downloading the podcast at home with good internet and then have them on the road on regions where even the radio waves don't get :) It would be great !

**Comment by Sn8z** [comment]
@rivman I'm currently working on migrating from AngularJS to Angular 7 which might take a while :dancer: but I've offline playback at the top of my Todo-list when I reach a point where I can start adding features again.
I'm trying to put as much time as possible into it atm but I can't give an ETA just yet, it all depends on how much time I've in the coming weeks :)

**Comment by Sn8z** [comment]
So after a long wait there's now a new version of Poddr (2.0.0) which introduces basic offline functionality :champagne: 
It's in early stages and I'm looking for feedback regarding it.
There will be improvements when it comes to download feedback etc. but if you have any more ideas feel free to open a new issue to discuss things :dancer:
