### ISSUE TITLE
Bug: Build Error on dev branch

### ISSUE THREAD

**Issue by yougotwill** [Sn8z/Poddr#660]
**Describe the bug**
Hi, was attempting to build the dev branch so I can have a go at adding a feature. This error came up when trying to build the `dev` branch.

```
ERROR in app/settings/settings.component.ts:41:50 - error TS2339: Property 'getFile' does not exist on type 'IFileTransport'.

41  public logStorage: string = log.transports.file.getFile().path;
                                                    ~~~~~~~
app/settings/settings.component.ts:132:42 - error TS2345: Argument of type '{ buttonLabel: string; filters: { name: string; extensions: string[]; }[]; properties: string[]; }' is not assignable to parameter of type 'OpenDialogOptions'.
  Types of property 'properties' are incompatible.
    Type 'string[]' is not assignable to type '("openFile" | "openDirectory" | "multiSelections" | "showHiddenFiles" | "createDirectory" | "promptToCreate" | "noResolveAliases" | "treatPackageAsDirectory")[]'.
      Type 'string' is not assignable to type '"openFile" | "openDirectory" | "multiSelections" | "showHiddenFiles" | "createDirectory" | "promptToCreate" | "noResolveAliases" | "treatPackageAsDirectory"'.

132  	const filepath = dialog.showOpenDialog(options);
     	                                       ~~~~~~~

error Command failed with exit code 1.
```

**To Reproduce**
1. Checkout `dev` branch
2. Run `yarn install`
3. Run `yarn start`

**Expected behavior**
App builds successfully on `dev` branch.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 10.14.6

**Additional context**

**Comment by Sn8z** [comment]
@yougotwill Will take a look at this when I've got the time for it! :) I currently only have an older Macbook Pro to try to reproduce the error on so it might take a while to debug.

**Comment by yougotwill** [comment]
No problem. Thanks for looking into it. I'm not super experienced with TS which makes debugging more difficult.

**Comment by yougotwill** [comment]
`master` builds fyi so I'll attempt a simple PR or two and just check there are no conflicts with the `dev` branch code.

**Comment by yougotwill** [comment]
Successfully built today after getting the latest commits! Will close this issue
