### ISSUE TITLE
Podcast get's found but nothing displayed in details

### ISSUE THREAD

**Issue by swschilke** [Sn8z/Poddr#668]
Hallo,
it happend to more then one podcast, but as an example: search for Best Smooth Jazz, select it and in the detail view --> nothing
See attached
Regards
sws
![bsj0](https://user-images.githubusercontent.com/13233922/82557695-80ecd780-9b6c-11ea-8ef0-feef8faf2b63.png)
![bsj1](https://user-images.githubusercontent.com/13233922/82557699-834f3180-9b6c-11ea-97ec-a79c8b4b5fbc.png)

**Comment by swschilke** [comment]
Might be similar to #638

**Comment by Sn8z** [comment]
Thanks for the detailed report but as you said this is tracked in #638 :smile:
