### ISSUE TITLE
Bug: search result switch to detail, go back to list and you are at the top

### ISSUE THREAD

**Issue by swschilke** [Sn8z/Poddr#670]
**Describe the bug**
In a search result you have e.g. 100 results. you scroll down (the scrollbar is not very good visibel btw) if you click on the 75th podcast to see the details and you go back to the result list you are back to the top 

**Expected behavior**
click on 75th podcast see details and if you go back to the search result you should be again around the 75th podcast and not at the top. Scrollbar should be visible as well

**Desktop (please complete the following information):**
win10

**Comment by swschilke** [comment]
Similar description to #515

**Comment by Sn8z** [comment]
Yep, I'm gonna close this one and keep #515 open for any discussions regarding this :man_dancing:
