### ISSUE TITLE
Feature Request: OPML Import / Export

### ISSUE THREAD

**Issue by swschilke** [Sn8z/Poddr#673]
**Is your feature request related to a problem? Please describe.**
It yould be nice if I could export the OMPL at my mobile podcatcher AntennaPod and import this to Poddr and vice versa, i.e. export the OPML from my Poddr and share ist with someone else.

**Describe the solution you'd like**
All Fav's (subscribed Podcasts) or a selection can exported to a OPML file or a OMPL file can be imported and the the podcasts you want to take over to the favorites get marked and stored.

**Describe alternatives you've considered**

**Additional context**
goof to keep subscriptions snyced between different podcatchers

**Comment by Sn8z** [comment]
This has been discussed in #492 and there's currently an early implementation on the dev branch that will be included in the next release.
