### ISSUE TITLE
Hello! Graphic Designer here!

### ISSUE THREAD

**Issue by radudang** [Sn8z/Poddr#70]
First thing first I must say that I love your application.
I'm a graphic designer with some experience in my back and i'm looking to change my portofolio a little.
So, i'm looking over nice apps/project who have a logo that can be improved. I would love to make something for you . If you are interested please respond here or contact me on 
radudangratian@gmail.com

Best regards, Radu Dan!

Here is my instagram profile where you can see my recent work : 

https://www.instagram.com/radudan93/

**Comment by Sn8z** [comment]
Hi there @radudang :)
Thanks for the kind words! I've actually been thinking about the logo and have intended to improve it.
I will close this issue and send a mail your way asap as I think your instagram looks really good!

// Sn8z
