### ISSUE TITLE
Extended Search for Podcast

### ISSUE THREAD

**Issue by swschilke** [Sn8z/Poddr#732]
Similar to the Top 50 / Country / Genre selection an (extended) search for Podcasts in a certain language or from a certain country would be cool. Also digging/drilling for the genre (Apple Podcast Directory) for all genres  (I think you can list three for each podcast).

**Comment by Sn8z** [comment]
@swschilke No worries, your feedback is valuable even if it's duplicated :wink: 
I haven't forgotten about it there's just a lot of different things going around atm.
I'll close this issue and refer all discussions regarding improved search features to #669 :man_dancing:
