### ISSUE TITLE
Feature Request: Poddr on Raspberry Pi (3 or higher)

### ISSUE THREAD

**Issue by swschilke** [Sn8z/Poddr#751]
It would be great to have a version of Poddr for Raspberry Pi

Similar to the other Linux versions a ARM based version could be offered

Maybe a Docker Image?!?

**Comment by Sn8z** [comment]
There's already a snap version that can be run on the Raspberry Pi so I don't intend on supporting yet another version at this point in time.

**Comment by swschilke** [comment]
> There's already a snap version that can be run on the Raspberry Pi so I don't intend on supporting yet another version at this point in time.

I didn't know that snap's work on Intel and ARM
