### ISSUE TITLE
Useability

### ISSUE THREAD

**Issue by notrednamc** [Sn8z/Poddr#90]
Is there a way to add podcasts that do not return in search? Is there a user guide?

**Comment by Sn8z** [comment]
Hi @notrednamc!
At this moment it's not possible to manually add podcasts but it will be implemented in the upcoming 1.1.0 version which is under development right now and it should be released sometime this february :dancer: 

At this moment there's no type of guide but it's great feedback and I'll make sure to make one after 1.1.0 is released! I'll probably make it available at the [website](https://sn8z.github.io/Poddr/) or the README for this repo, not yet sure. If there's something you need an answer to right now I'll gladly respond here :)

**Comment by notrednamc** [comment]
That sounds great. Alot of the podcasts I listen too aren't returned in the
search so that would be great. I didn't know if I missed the README lol.

All is good. Thanks

**Comment by Sn8z** [comment]
Do you have any examples of podcasts that doesn't show up? It can be useful to know a few for testing purposes during development :D

No worries, there really should be a type of guide available besides the README since not every user knows what GitHub is.

**Comment by notrednamc** [comment]
Black Hills Information Security Podcast is one that I listen to that did now show up in the search. I tried a general "infosec" search term too.

**Comment by Sn8z** [comment]
@notrednamc I've just released version 1.1.0 which includes the possibility to manually add podcast feeds on the favourites page by pressing the plus button in the upper right corner!
I'll close this issue and open a new separate one regarding a user guide :)

**Comment by notrednamc** [comment]
That's awesome. Thanks for the update!!!
